# Generated by Django 4.0.2 on 2022-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='designation',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='image',
            name='salary',
            field=models.IntegerField(default=None),
        ),
    ]
